name: Docker workflow

on: 
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login to Docker hub
        uses: docker/login-action@v3
        with:
          username: sooscode
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: | 
          docker compose build
          docker compose push